// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0vHqAyWhmFJmHanttCyRK5BJUvVoAldM',
    appId: '1:877896429179:web:a44e25041ffc160a713cde',
    messagingSenderId: '877896429179',
    projectId: 'weatherapp-29fee',
    authDomain: 'weatherapp-29fee.firebaseapp.com',
    storageBucket: 'weatherapp-29fee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxK5Cw9-q2PjNmNoKxacBWZ3wtkq1_8Y',
    appId: '1:877896429179:android:9c8de716257d2428713cde',
    messagingSenderId: '877896429179',
    projectId: 'weatherapp-29fee',
    storageBucket: 'weatherapp-29fee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGZnmzj9QQNmLC1ASGlCWeiQ91b4AIsY4',
    appId: '1:877896429179:ios:b52191a3a5ecb9d3713cde',
    messagingSenderId: '877896429179',
    projectId: 'weatherapp-29fee',
    storageBucket: 'weatherapp-29fee.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGZnmzj9QQNmLC1ASGlCWeiQ91b4AIsY4',
    appId: '1:877896429179:ios:b52191a3a5ecb9d3713cde',
    messagingSenderId: '877896429179',
    projectId: 'weatherapp-29fee',
    storageBucket: 'weatherapp-29fee.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0vHqAyWhmFJmHanttCyRK5BJUvVoAldM',
    appId: '1:877896429179:web:810bc1e234d3cc98713cde',
    messagingSenderId: '877896429179',
    projectId: 'weatherapp-29fee',
    authDomain: 'weatherapp-29fee.firebaseapp.com',
    storageBucket: 'weatherapp-29fee.firebasestorage.app',
  );

}